### ISSUE TITLE
fix install bug

### ISSUE THREAD

**Issue by bamtercelboo** [ShannonAI/glyce#1]
Hi, clone project is not exist.
change to:
    https://github.com/ShannonAI/glyce.git
    git@github.com:ShannonAI/glyce.git

**Comment by jiweil** [comment]
/Users/lili/Desktop/Screen Shot 2019-05-31 at 10.21.43 AM.png

**Comment by jiweil** [comment]
十分感谢～这就修改一下README～我们之后还会push一版最新的～

**Comment by jiweil** [comment]
十分感谢～这就修改一下README～我们之后还会push一版最新的～
