### ISSUE TITLE
About config

### ISSUE THREAD

**Issue by Decalogue** [ShannonAI/glyce#1]
Hi!
I want to know about 'parser.add_argument("--config_path", default="/home/lixiaoya/dataset/", type=str)', where is your config file? I didn't find it in the project.
Thank you so much!

**Comment by Decalogue** [comment]
self.glyph_transformer = GlyphTransformer(config, num_labels=num_labels)
# config involves here 
# 1. config.glyph_config 
# 2. config.bert_config 
# 3. transformer_config 

the config didn't appear in args.config_path of run_bert_glyce_classifier.py

**Comment by jiweil** [comment]
These files will be posted really soon ! !
