### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by YuChen17Heaven** [ShannonAI/glyce#3]
hi, I ran your code glyce/glyce/bin/run_bert_glyce_classifier.py, but there some errors I found.
first: glyce/glyce/dataset_readers/bert_data_utils.py is empty
second: i couldn't find file " glyce.data.data_utils import *" that you want to import
third: "from glyce.models.glyce_bert.glyce_bert_classifier import GlyphBertClassifier " is it should be "from glyce.models.glyce_bert.glyce_bert_classifier import GlyceBertClassifier"?

**Comment by ghost** [comment]
I will check these issues later today. Reply to you at the latest tomorrow. Thanks a lot.

**Comment by YuChen17Heaven** [comment]
hi, I have another question. If i want to train the single sentence classification, i just need to change the    
data_processor in run_bert_glyce_classifier.py, right?

**Comment by ghost** [comment]
Yes. You should change 【data_processor】 if you would like to apply Glyce-BERT to a single sentence classification dataset. I will upload the latest code these two days. Thanks for your focus. :-)

**Comment by YuChen17Heaven** [comment]
I'm sorry to bother you, but there are still some problems I can't solve:
Traceback (most recent call last):
  File "run_bert_glyce_classifier.py", line 29, in <module>
    from glyce.models.glyce_bert.glyce_bert_classifier import GlyphBertClassifier
  File "/home/youmin/syc/glyce-master/glyce/models/glyce_bert/glyce_bert_classifier.py", line 29, in <module>
    from glyce.layers.glyce_transformer import GlyphTransformer 
  File "/home/youmin/syc/glyce-master/glyce/layers/glyce_transformer.py", line 38, in <module>
    from glyce.layers.glyph_position_embed import GlyphPositionEmbedder
  File "/home/youmin/syc/glyce-master/glyce/layers/glyph_position_embed.py", line 38, in <module>
    from glyce.glyph_embedding.models.glyph_char import CharGlyphEmbedding
ModuleNotFoundError: No module named 'glyce.glyph_embedding'

**Comment by stepperL** [comment]
I will check and update all the files tonight. You will be notified of any updates. Thanks for your focus!!!!!

**Comment by stepperL** [comment]
I will check all the files tonight. You will be notified of any updates. Many thanks for your focus!!!!!

**Comment by ghost** [comment]
I will check tonight. You will be notified of any updates. Many thanks for your focus!!!!!

**Comment by zhaolulul** [comment]
from glyce.data.data_utils import *  i could not find  dir data  and file  data_utils.ModuleNotFoundError: No module named ''glyce.data.data_utils'

**Comment by zhaolulul** [comment]
hi,i am sorry to bother you ,but when i run_bert_glyce_tagger.py , I found pinyin_vocab.json to be the same as  wubi_vocab.json. I was a little strange.Maybe there were some mistakes. I hope to reply.

**Comment by zhaolulul** [comment]
I'm sorry to bother you again. When I ran that code, I found that you took bert's word2id as input, but dict_word ['idx2char'] used the other one. There should be a problem here. Could you check if you have time? If you have time, please reply as soon as possible.

**Comment by ghost** [comment]
Thanks for your issues. Please pull the latest code. :-)
