### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by mmlab-iie** [ShannonAI/glyce#4]
Dear authors, 

I run the code and could not find the file "pypinyin.py".

Meanwhile I could not find the scripts as mentioned below:
<img width="901" alt="WX20190709-093729@2x" src="https://user-images.githubusercontent.com/52650411/60853141-5bddc780-a22d-11e9-8d57-7fee673659ba.png">

Hope your reply! Thanks!

**Comment by ghost** [comment]
pypinyin is one of package dependencies for Glyce. Install via `pip install pypinyin==0.34.1`

**Comment by ghost** [comment]
You should install all package dependencies by `pip install -r requirements.txt`
