### ISSUE TITLE
hi,i am sorry to bother you ,but when i run_bert_glyce_tagger.py , I found pinyin_vocab.json to be the same as wubi_vocab.json. I was a little strange.Maybe there were some mistakes. I hope to reply.

### ISSUE THREAD

**Issue by zhaolulul** [ShannonAI/glyce#7]

**Comment by ghost** [comment]
I will check it and get back to you as soon as possible. Many thanks.

**Comment by ghost** [comment]
These two files are not the same. Please pull the latest code. Many thanks.

**Comment by ghost** [comment]
The path to `pinyin_vocab.json` and `wubi_vocab.json` could be found in `/glyce/utils/comonents.py`. You can print the path and see what happens.

**Comment by zhaolulul** [comment]
Thank you so much !!!
