### ISSUE TITLE
you took inputids use bert's word2id ,then obtained word glyce you took dict_word ['idx2char'] 

### ISSUE THREAD

**Issue by zhaolulul** [ShannonAI/glyce#8]
I'm sorry to bother you again. When I ran that code, I found that you took inputids use bert's word2id  but dict_word ['idx2char'] used the other one. There should be a problem here. Could you check if you have time? If you have time, please reply as soon as possible.

**Comment by ghost** [comment]
I will check it and get back to you as soon as possible. Many thanks.

**Comment by ghost** [comment]
Thanks for your issue. We already fix this. Please pull the latest code.

**Comment by zhaolulul** [comment]
thank you so much
